[package]
name = "symsrv"
version = "0.2.0"
edition = "2021"
authors = ["Markus Stange <mstange@themasta.com>"]
license = "MIT/Apache-2.0"
description = "A Microsoft symsrv symbol server consumer (downloader + cache)"
repository = "https://github.com/mstange/symsrv/"
readme = "README.md"
exclude = ["/.github", "/tests"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
reqwest = { version = "0.11.10", default-features = false, features = [
    "rustls-tls",
    "gzip",
    "brotli",
    "deflate"
] }
bytes = "1.1.0"
dirs = "4.0"
tokio = { version = "1.17.0", features = ["fs"] }
thiserror = "1.0.26"
cab = "0.4.0"
memmap2 = "0.5.0"

[dev-dependencies]
tempfile = "3.1.0"
tokio = { version = "1.17.0", features = ["macros"] }
mockito = "0.32.2"
